/** Single source of truth for slotTrail.action enum values. */
export const SLOT_TRAIL_ACTIONS = {
  ADD: "ADD",
  SUBTRACT: "SUBTRACT",
  BUFFER_APPLIED: "BUFFER_APPLIED",
  BUFFER_RELEASED: "BUFFER_RELEASED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_RETURNED: "ORDER_RETURNED",
  ADD_WITH_BUFFER: "ADD_WITH_BUFFER",
  ADD_WITH_BUFFER_RELEASE: "ADD_WITH_BUFFER_RELEASE",
  SUBTRACT_WITH_BUFFER: "SUBTRACT_WITH_BUFFER",
  SUBTRACT_WITH_BUFFER_RELEASE: "SUBTRACT_WITH_BUFFER_RELEASE",
  UPDATE: "UPDATE",
  SOWING_STARTED: "SOWING_STARTED",
  STOCK_REQUEST_ISSUED: "STOCK_REQUEST_ISSUED",
  SOWING_COMPLETED: "SOWING_COMPLETED",
  SOWING_CANCELLED: "SOWING_CANCELLED",
  SOWING_PRIMARY: "SOWING_PRIMARY",
  SOWING_OFFICE: "SOWING_OFFICE",
  SOWING_EXCESSIVE: "SOWING_EXCESSIVE",
  EXCESSIVE_SOWING_ADDED: "EXCESSIVE_SOWING_ADDED",
  STOCK_REQUEST_CREATED: "STOCK_REQUEST_CREATED",
  STOCK_REQUEST_CANCELLED: "STOCK_REQUEST_CANCELLED",
  GAP_COVERED: "GAP_COVERED",
  SOWING_IN_PROGRESS_CLEARED: "SOWING_IN_PROGRESS_CLEARED",
  PACKETS_RETURNED: "PACKETS_RETURNED",
  PACKETS_USED: "PACKETS_USED",
  SOWING_READY_DATE_MAPPED: "SOWING_READY_DATE_MAPPED",
  READY_DAYS_UPDATED: "READY_DAYS_UPDATED",
  ACTUAL_PLANTS_UPDATED: "ACTUAL_PLANTS_UPDATED",
  CLOSING_STOCK_UPDATED: "CLOSING_STOCK_UPDATED",
  AVAILABLE_PLANTS_UPDATED: "AVAILABLE_PLANTS_UPDATED",
  EARLY_DISPATCH_OUT: "EARLY_DISPATCH_OUT",
  EARLY_DISPATCH_IN: "EARLY_DISPATCH_IN",
  EARLY_DISPATCH_REVERT_OUT: "EARLY_DISPATCH_REVERT_OUT",
  EARLY_DISPATCH_REVERT_IN: "EARLY_DISPATCH_REVERT_IN",
};

export const SLOT_TRAIL_ACTION_ENUM = Object.values(SLOT_TRAIL_ACTIONS);

/** Stock field → trail action (used by PUT /slots/:id and bulk stock entry). */
export const STOCK_TRAIL_FIELD_ACTIONS = {
  actualPlants: SLOT_TRAIL_ACTIONS.ACTUAL_PLANTS_UPDATED,
  closingStock: SLOT_TRAIL_ACTIONS.CLOSING_STOCK_UPDATED,
  availablePlants: SLOT_TRAIL_ACTIONS.AVAILABLE_PLANTS_UPDATED,
};

export const STOCK_TRAIL_ACTION_LIST = Object.values(STOCK_TRAIL_FIELD_ACTIONS);

export const SLOT_TRAIL_ACTIVITY_NAMES = {
  [SLOT_TRAIL_ACTIONS.ADD]: "Plants Added",
  [SLOT_TRAIL_ACTIONS.SUBTRACT]: "Plants Subtracted",
  [SLOT_TRAIL_ACTIONS.BUFFER_APPLIED]: "Buffer Applied",
  [SLOT_TRAIL_ACTIONS.BUFFER_RELEASED]: "Buffer Released",
  [SLOT_TRAIL_ACTIONS.ORDER_CANCELLED]: "Order Cancelled",
  [SLOT_TRAIL_ACTIONS.ORDER_RETURNED]: "Order Returned",
  [SLOT_TRAIL_ACTIONS.ADD_WITH_BUFFER]: "Plants Added with Buffer",
  [SLOT_TRAIL_ACTIONS.ADD_WITH_BUFFER_RELEASE]: "Plants Added with Buffer Release",
  [SLOT_TRAIL_ACTIONS.SUBTRACT_WITH_BUFFER]: "Plants Subtracted with Buffer",
  [SLOT_TRAIL_ACTIONS.SUBTRACT_WITH_BUFFER_RELEASE]: "Plants Subtracted with Buffer Release",
  [SLOT_TRAIL_ACTIONS.UPDATE]: "Slot Updated",
  [SLOT_TRAIL_ACTIONS.SOWING_STARTED]: "Sowing Started",
  [SLOT_TRAIL_ACTIONS.STOCK_REQUEST_ISSUED]: "Stock Request Issued",
  [SLOT_TRAIL_ACTIONS.SOWING_COMPLETED]: "Sowing Completed",
  [SLOT_TRAIL_ACTIONS.SOWING_CANCELLED]: "Sowing Cancelled",
  [SLOT_TRAIL_ACTIONS.SOWING_PRIMARY]: "Primary Location Sowing",
  [SLOT_TRAIL_ACTIONS.SOWING_OFFICE]: "Office Location Sowing",
  [SLOT_TRAIL_ACTIONS.SOWING_EXCESSIVE]: "Excessive Sowing",
  [SLOT_TRAIL_ACTIONS.EXCESSIVE_SOWING_ADDED]: "Excessive Sowing Added",
  [SLOT_TRAIL_ACTIONS.STOCK_REQUEST_CREATED]: "Stock Request Created",
  [SLOT_TRAIL_ACTIONS.STOCK_REQUEST_CANCELLED]: "Stock Request Cancelled",
  [SLOT_TRAIL_ACTIONS.GAP_COVERED]: "Gap Covered",
  [SLOT_TRAIL_ACTIONS.SOWING_IN_PROGRESS_CLEARED]: "Sowing In Progress Cleared",
  [SLOT_TRAIL_ACTIONS.PACKETS_RETURNED]: "Packets Returned",
  [SLOT_TRAIL_ACTIONS.PACKETS_USED]: "Packets Used",
  [SLOT_TRAIL_ACTIONS.SOWING_READY_DATE_MAPPED]: "Sowing Ready Date Mapped",
  [SLOT_TRAIL_ACTIONS.READY_DAYS_UPDATED]: "Ready Days Updated",
  [SLOT_TRAIL_ACTIONS.ACTUAL_PLANTS_UPDATED]: "Actual Plants Updated",
  [SLOT_TRAIL_ACTIONS.CLOSING_STOCK_UPDATED]: "Closing Stock Updated",
  [SLOT_TRAIL_ACTIONS.AVAILABLE_PLANTS_UPDATED]: "Available Plants Updated",
  [SLOT_TRAIL_ACTIONS.EARLY_DISPATCH_OUT]: "Released for cross-slot dispatch",
  [SLOT_TRAIL_ACTIONS.EARLY_DISPATCH_IN]: "Cross-slot dispatch booking",
  [SLOT_TRAIL_ACTIONS.EARLY_DISPATCH_REVERT_OUT]: "Cross-slot dispatch reverted (out)",
  [SLOT_TRAIL_ACTIONS.EARLY_DISPATCH_REVERT_IN]: "Cross-slot dispatch reverted (in)",
};

export function getSlotTrailActivityName(action) {
  if (!action) return "Unknown Activity";
  return SLOT_TRAIL_ACTIVITY_NAMES[action] || String(action).replace(/_/g, " ");
}
