/** Account codes — seed in chart_of_accounts */
export const ACCOUNT_CODES = {
  AR_FARMER: "AR_FARMER",
  AR_AGRI: "AR_AGRI",
  AR_DEALER: "AR_DEALER",
  CASH: "CASH",
  BANK_ICICI: "BANK_ICICI",
  SALES_PLANTS: "SALES_PLANTS",
  SALES_AGRI: "SALES_AGRI",
  SALES_RETURN: "SALES_RETURN",
  CUSTOMER_ADVANCE: "CUSTOMER_ADVANCE",
  SUSPENSE_BANK: "SUSPENSE_BANK",
  DEALER_WALLET: "DEALER_WALLET",
  COMMISSION_EXPENSE: "COMMISSION_EXPENSE",
  TRANSPORT_EXPENSE: "TRANSPORT_EXPENSE",
  PAYMENT_CLEARING: "PAYMENT_CLEARING",
};

export const ACCOUNT_TYPES = {
  ASSET: "ASSET",
  LIABILITY: "LIABILITY",
  EQUITY: "EQUITY",
  INCOME: "INCOME",
  EXPENSE: "EXPENSE",
};

export const VOUCHER_TYPES = {
  SALES_INVOICE: "SALES_INVOICE",
  RECEIPT: "RECEIPT",
  PAYMENT: "PAYMENT",
  CREDIT_NOTE: "CREDIT_NOTE",
  DEBIT_NOTE: "DEBIT_NOTE",
  CONTRA: "CONTRA",
  JOURNAL: "JOURNAL",
  REFUND: "REFUND",
  ADJUSTMENT: "ADJUSTMENT",
  REVERSAL: "REVERSAL",
};

export const VOUCHER_STATUS = {
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  POSTED: "POSTED",
  REVERSED: "REVERSED",
  CANCELLED: "CANCELLED",
};

export const EVENT_STATUS = {
  PENDING: "PENDING",
  PROCESSED: "PROCESSED",
  REJECTED: "REJECTED",
  FAILED: "FAILED",
};

export const PARTY_TYPES = {
  FARMER: "FARMER",
  AGRI_CUSTOMER: "AGRI_CUSTOMER",
  DEALER: "DEALER",
  NONE: "NONE",
};

export const FINANCIAL_EVENT_TYPES = {
  FARMER_ORDER_CREATED: "FARMER_ORDER_CREATED",
  FARMER_PAYMENT_COLLECTED: "FARMER_PAYMENT_COLLECTED",
  FARMER_PAYMENT_REVERSED: "FARMER_PAYMENT_REVERSED",
  FARMER_ORDER_DELTA: "FARMER_ORDER_DELTA",
  FARMER_ORDER_CANCEL: "FARMER_ORDER_CANCEL",
  FARMER_ORDER_REOPEN: "FARMER_ORDER_REOPEN",
  FARMER_DISPATCH_RETURN: "FARMER_DISPATCH_RETURN",
  FARMER_ADVANCE_TRANSFER: "FARMER_ADVANCE_TRANSFER",
  FARMER_PAYMENT_TRANSFER: "FARMER_PAYMENT_TRANSFER",
  FARMER_MANUAL_ADJUSTMENT: "FARMER_MANUAL_ADJUSTMENT",
  AGRI_ORDER_CREATED: "AGRI_ORDER_CREATED",
  AGRI_PAYMENT_COLLECTED: "AGRI_PAYMENT_COLLECTED",
  AGRI_PAYMENT_REVERSED: "AGRI_PAYMENT_REVERSED",
  AGRI_ORDER_DELTA: "AGRI_ORDER_DELTA",
  AGRI_SALES_RETURN: "AGRI_SALES_RETURN",
  AGRI_MANUAL_ADJUSTMENT: "AGRI_MANUAL_ADJUSTMENT",
  DEALER_ORDER_BOOKING: "DEALER_ORDER_BOOKING",
  DEALER_RECEIVABLE_PAYMENT: "DEALER_RECEIVABLE_PAYMENT",
  DEALER_WALLET_MOVEMENT: "DEALER_WALLET_MOVEMENT",
  DEALER_COMMISSION_SETTLEMENT: "DEALER_COMMISSION_SETTLEMENT",
  BANK_STATEMENT_UNMATCHED: "BANK_STATEMENT_UNMATCHED",
  BANK_PAYMENT_VERIFIED: "BANK_PAYMENT_VERIFIED",
};

export const DEFAULT_BRANCH_ID = "default";
